[package]
name = "foo"
edition = "2021"

[dependencies]
miniquad = { git = "https://github.com/not-fl3/miniquad" }
log = "0.4.22"
smol = "2.0.1"
async-channel = "2.3.1"
rand = "0.8.5"
simplelog = "0.12.1"

